// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
import { blogPosts } from "npm:@/data/blogPosts";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List every published Kirangi Dogs blog post with slug, title, subtitle, category, date and estimated read time. Use `get_blog_post` to fetch the full article body by slug.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = blogPosts.map(({ slug, title, subtitle, category, date, readTime }) => ({
      slug,
      title,
      subtitle,
      category,
      date,
      readTime,
      url: `https://kirangidogs.com/blog/${slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { posts: items }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^3.25.76";
import { blogPosts as blogPosts2 } from "npm:@/data/blogPosts";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single Kirangi Dogs blog post (title, metadata, and full markdown body) by its slug. Use `list_blog_posts` to discover valid slugs.",
  inputSchema: {
    slug: z.string().min(1).describe("The blog post slug, e.g. `choosing-a-protection-dog`.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const post = blogPosts2.find((p) => p.slug === slug);
    if (!post) {
      return {
        content: [{ type: "text", text: `No blog post found with slug "${slug}".` }],
        isError: true
      };
    }
    const { icon: _icon, ...data } = post;
    const payload = { ...data, url: `https://kirangidogs.com/blog/${post.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { post: payload }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";
var SERVICES = [
  {
    name: "Working-Line German Shepherd Puppies",
    description: "Champion-bloodline working-line German Shepherd puppies bred for protection, service, and family companionship."
  },
  {
    name: "Black Russian Terrier Puppies",
    description: "Health-tested Black Russian Terrier puppies from imported bloodlines. The next litter is expected in December."
  },
  {
    name: "Personal & Family Protection Dogs",
    description: "Fully trained protection dogs selected and developed for nerve stability, confidence, and controlled defense work."
  },
  {
    name: "Service & Assistance Dogs",
    description: "Service and assistance dogs carefully trained for individuals living with mobility challenges, PTSD, ADHD, anxiety, and other conditions. Specialties include psychiatric dogs, mobility dogs, medical-alert dogs, and mobility tasks."
  },
  {
    name: "Professional Dog Training",
    description: "Obedience, protection, and specialty task training led by Joseph Chege \u2014 a professional dog trainer and Occupational Therapist with 10+ years of experience. Services extend beyond Kenya to the wider East African Community."
  }
];
var list_services_default = defineTool3({
  name: "list_services",
  title: "List services",
  description: "List the services Kirangi Dogs offers: puppies, protection dogs, service/assistance dogs, and professional training.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
var CONTACT = {
  business: "Kirangi Dogs",
  location: "Kenya (serving international clients across the East African Community and beyond)",
  phone: "+254-785-535-569",
  email: "kirangidogs@gmail.com",
  whatsapp: "https://wa.me/254785535569",
  website: "https://kirangidogs.com",
  blog: "https://kirangidogs.com/blog",
  puppyReservations: "https://kirangidogs.com/puppy-form"
};
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get Kirangi Dogs' public contact details: phone, email, WhatsApp, website, blog, and puppy reservation link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/tools/submit-puppy-booking.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^3.25.76";
var FUNCTION_URL = "https://fqcsnlghwugkkwsegpsb.supabase.co/functions/v1/submit-puppy-booking";
var ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxY3NubGdod3Vna2t3c2VncHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjYzNDAsImV4cCI6MjA3MzI0MjM0MH0.qQaU-SyNA4Jg2c2VZy_FKKNis-Vcxzb-8Wlbp6t--cQ";
var submit_puppy_booking_default = defineTool5({
  name: "submit_puppy_booking",
  title: "Submit puppy booking inquiry",
  description: "Submit a reservation request for the upcoming Black Russian Terrier litter (expected December). Sends the inquiry to Kirangi Dogs and emails the requester a confirmation.",
  inputSchema: {
    name: z2.string().min(1).describe("Full name of the person making the reservation."),
    phone: z2.string().min(5).describe("Contact phone number (include country code)."),
    email: z2.string().email().describe("Email address for the confirmation reply."),
    preferred_sex: z2.enum(["Male", "Female", "Either"]).describe("Preferred puppy sex."),
    notes: z2.string().optional().describe("Optional additional questions or notes for the breeder.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input) => {
    try {
      const res = await fetch(FUNCTION_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: ANON_KEY,
          Authorization: `Bearer ${ANON_KEY}`
        },
        body: JSON.stringify(input)
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        return {
          content: [
            {
              type: "text",
              text: `Booking failed (${res.status}): ${data?.error ?? "unknown error"}`
            }
          ],
          isError: true
        };
      }
      return {
        content: [
          {
            type: "text",
            text: `Booking submitted. Kirangi Dogs will reply within 24-48 hours. Booking ID: ${data?.bookingId ?? "n/a"}`
          }
        ],
        structuredContent: data
      };
    } catch (err) {
      return {
        content: [
          { type: "text", text: `Network error submitting booking: ${err.message}` }
        ],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/submit-contact-inquiry.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z3 } from "npm:zod@^3.25.76";
var FUNCTION_URL2 = "https://fqcsnlghwugkkwsegpsb.supabase.co/functions/v1/send-contact-email";
var ANON_KEY2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxY3NubGdod3Vna2t3c2VncHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjYzNDAsImV4cCI6MjA3MzI0MjM0MH0.qQaU-SyNA4Jg2c2VZy_FKKNis-Vcxzb-8Wlbp6t--cQ";
var submit_contact_inquiry_default = defineTool6({
  name: "submit_contact_inquiry",
  title: "Send contact inquiry",
  description: "Send a general contact-form inquiry to Kirangi Dogs (delivered by email). Use for questions about training, protection dogs, assistance dogs, or general information \u2014 use `submit_puppy_booking` for puppy reservations.",
  inputSchema: {
    name: z3.string().min(1).describe("Full name of the sender."),
    email: z3.string().email().describe("Reply-to email address."),
    phone: z3.string().optional().describe("Optional contact phone number."),
    message: z3.string().min(1).describe("The inquiry or question.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input) => {
    try {
      const res = await fetch(FUNCTION_URL2, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: ANON_KEY2,
          Authorization: `Bearer ${ANON_KEY2}`
        },
        body: JSON.stringify(input)
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        return {
          content: [
            {
              type: "text",
              text: `Contact submission failed (${res.status}): ${data?.error ?? "unknown error"}`
            }
          ],
          isError: true
        };
      }
      return {
        content: [
          { type: "text", text: "Inquiry sent. Kirangi Dogs will reply by email." }
        ],
        structuredContent: data
      };
    } catch (err) {
      return {
        content: [
          { type: "text", text: `Network error sending inquiry: ${err.message}` }
        ],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kirangi-dogs-mcp",
  title: "Kirangi Dogs",
  version: "0.1.0",
  instructions: "Public MCP server for Kirangi Dogs (kirangidogs.com) \u2014 Kenya's premier breeder and trainer of working-line German Shepherds and Black Russian Terriers. Read blog articles, list services, get contact info, submit a puppy reservation for the upcoming December Black Russian Terrier litter, or send a general contact inquiry.",
  tools: [
    list_blog_posts_default,
    get_blog_post_default,
    list_services_default,
    get_contact_info_default,
    submit_puppy_booking_default,
    submit_contact_inquiry_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
