// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqcsnlghwugkkwsegpsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxY3NubGdod3Vna2t3c2VncHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjYzNDAsImV4cCI6MjA3MzI0MjM0MH0.qQaU-SyNA4Jg2c2VZy_FKKNis-Vcxzb-8Wlbp6t--cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});